import { MembershipStatus, PaymentMethod } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, IsUUID, Max, MaxLength, Min, ValidateNested } from 'class-validator';
import { CreateMemberDto } from '../members/members.dto';
export class CreateMembershipDto { @IsOptional() @IsUUID() clientMembershipId?: string; @IsOptional() @IsUUID() clientPaymentId?: string; @IsOptional() @IsUUID() clientMutationId?: string; @IsOptional() @IsDateString() occurredAt?: string; @IsString() memberId: string; @IsString() planId: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(24) periodCount?: number; @IsOptional() @IsDateString() startDate?: string; @IsOptional() @Type(() => Number) @IsNumber({ maxDecimalPlaces: 2 }) @Min(0.01) initialPayment?: number; @IsOptional() @IsEnum(PaymentMethod) paymentMethod?: PaymentMethod; @IsOptional() @IsString() @MaxLength(100) reference?: string; }
export class AssignGymMembershipDto { @IsOptional() @IsUUID() clientMembershipId?: string; @IsOptional() @IsUUID() clientPaymentId?: string; @IsOptional() @IsUUID() clientMutationId?: string; @IsOptional() @IsDateString() occurredAt?: string; @IsString() planId: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(24) periodCount?: number; @IsOptional() @IsDateString() startDate?: string; @IsOptional() @Type(() => Number) @IsNumber({ maxDecimalPlaces: 2 }) @Min(0.01) initialPayment?: number; @IsOptional() @IsEnum(PaymentMethod) paymentMethod?: PaymentMethod; @IsOptional() @IsString() @MaxLength(100) reference?: string; }
export class CreateMemberWithMembershipDto { @ValidateNested() @Type(() => CreateMemberDto) member: CreateMemberDto; @ValidateNested() @Type(() => AssignGymMembershipDto) membership: AssignGymMembershipDto; }
export class UpdateGymMembershipDto { @IsOptional() @IsString() planId?: string; @IsOptional() @IsDateString() startDate?: string; @IsOptional() @IsDateString() endDate?: string; @IsOptional() @IsEnum(MembershipStatus) status?: MembershipStatus; }
export class RenewMembershipDto { @IsOptional() @IsUUID() clientMembershipId?: string; @IsOptional() @IsUUID() clientPaymentId?: string; @IsOptional() @IsUUID() clientMutationId?: string; @IsOptional() @IsDateString() occurredAt?: string; @IsOptional() @IsString() planId?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(24) periodCount?: number; @IsOptional() @Type(() => Number) @IsNumber({ maxDecimalPlaces: 2 }) @Min(0.01) initialPayment?: number; @IsOptional() @IsEnum(PaymentMethod) paymentMethod?: PaymentMethod; @IsOptional() @IsString() @MaxLength(100) reference?: string; }
