CREATE TYPE "GymSubscriptionPlan" AS ENUM ('TRIAL', 'MONTHLY', 'ANNUAL');

ALTER TABLE "Gym"
ADD COLUMN "subscriptionPlan" "GymSubscriptionPlan" NOT NULL DEFAULT 'TRIAL',
ADD COLUMN "subscriptionTrialDays" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN "subscriptionStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "subscriptionEndsAt" TIMESTAMP(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '7 days');
